### ISSUE TITLE
首页的GoodList没有使用ListView.builder

### ISSUE THREAD

**Issue by see311** [MiYogurt/flower_flutter#3]
首页的`GoodList`没有使用`ListView.builder`构建的话如果商品列表加上加载更多的话会不会影响性能？父级的`ListView`也没有使用`ListView.builder`。商品列表是使用`Wrap`包裹的。
如何优化呢？
顺便，大佬放个支付二维码吧，请你喝咖啡

**Comment by MiYogurt** [comment]
ListView 是没法实现 2个一行的效果的，为什么会出现有性能问题的想法。二维码在 https://github.com/MiYogurt/nodelover-maps

**Comment by see311** [comment]
`ListView.builder`不是在滑动到屏幕中的时候才渲染么？如果商品变成无限加载的，没有用`ListView.builder`的话岂不是得一下全渲染出来？会不会越滚越卡？

**Comment by see311** [comment]
已扫码

**Comment by MiYogurt** [comment]
没看见是在屏幕才显示的注释，你可以用 GirdView 来做，或者自定义一个滚动列表，我之所以没有用滚动，是因为嵌套的滚动视图不太好控制，在 Android 下面这种嵌套的滚动也是需要手动进行修复的。

**Comment by MiYogurt** [comment]
我的新书 《Dart 快速实践》快要写完了，假如你还对 Dart 其他的领域的感兴趣可以关注下。

**Comment by see311** [comment]
已star
